<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="eureka">

  <xacro:include filename="$(find eureka_simulation)/urdf/inertial_macros.xacro"/>

  <xacro:property name="chassis_length" value="0.8"/>
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.3"/>
  <xacro:property name="chassis_mass" value="25.0"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_thickness" value="0.15"/>
  <xacro:property name="wheel_mass" value="4.0"/>
  <xacro:property name="wheel_offset_x" value="0.4"/>
  <xacro:property name="wheel_offset_y" value="0.4"/>
  <xacro:property name="wheel_offset_z" value="0.4"/>

  <xacro:include filename="materials.urdf.xacro"/>

  <link name="base_link">

  </link>

  <link name="chassis">
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="orange"/>
    </visual>
    <collision>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <link name="left_rear_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="left_middle_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="left_front_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="right_rear_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="right_middle_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="right_front_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <xacro:include filename="$(find eureka_simulation)/urdf/gazebo_material.urdf.xacro"/>

  <joint name="chassis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chassis"/>
      <origin xyz="${-chassis_length/2} 0 0"/>
  </joint>

  <joint name="left_rear_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_rear_wheel"/>
      <origin xyz="${-wheel_offset_x} ${wheel_offset_y} 0.02" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>


  <joint name="left_middle_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_middle_wheel"/>
      <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>

  <joint name="left_front_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_front_wheel"/>
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>

  <joint name="right_rear_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_rear_wheel"/>
      <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} 0.02" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>

  <joint name="right_middle_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_middle_wheel"/>
      <origin xyz="0 ${-wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>

  <joint name="right_front_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_front_wheel"/>
      <origin xyz="${wheel_offset_x} ${-wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>

  <xacro:include filename="sensor.urdf.xacro"/>

  <xacro:include filename="control.urdf.xacro"/>

  <xacro:include filename="gazebo_material.urdf.xacro"/>

</robot>
