controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    ack_cont:
      type: eureka_ackermann_controller/EurekaAckermannController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:

    publish_rate: 40.0

    half_wheelbase: 0.4
    middle_wheels_radius: 0.1
    middle_wheel_track: 0.8
    reference_timeout: 2.0
    rear_wheels_names: ['right_rear_wheel_joint', 'left_rear_wheel_joint']
    middle_wheels_names: ['right_middle_wheel_joint', 'left_middle_wheel_joint']
    front_wheels_names: ['right_front_wheel_joint', 'left_front_wheel_joint']
    open_loop: true
    enable_odom_tf: true
    velocity_rolling_window_size: 10
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: false
    use_stamped_vel: false