controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    ack_cont:
      type: eureka_ackermann_controller/EurekaAckermannController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:

    publish_rate: 40.0

    half_wheelbase: 0.4
    wheels_radius: 0.1
    wheel_track: 0.8
    reference_timeout: 2.0
    front_steer_mech_names: ['front_right_corner_joint', 'front_left_corner_joint']
    rear_steer_mech_names: ['back_right_corner_joint', 'back_left_corner_joint']
    rear_wheels_names: ['back_right_wheel_joint', 'back_left_wheel_joint']
    middle_wheels_names: ['mid_right_wheel_joint', 'mid_left_wheel_joint']
    front_wheels_names: ['front_right_wheel_joint', 'front_left_wheel_joint']
    open_loop: true
    enable_odom_tf: true
    velocity_rolling_window_size: 10
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: true
    use_stamped_vel: false